#!/usr/bin/env zsh

SSH_DIR="$HOME/.ssh"
# Create vault passwordfile
while [[ -z $pw ]]; do
    echo "Vault Password:"
    read pw
done

echo "Repeat Vault Password:"
read pw_check

# Check if passwords match
while [ "$pw" != "$pw_check" ]; do
    echo "Incorrect. Repeat Vault Password:"
    read pw_check
done

echo $pw > $HOME/.keys/scripts/pw

# Delete all existing encrypted keys
rm $HOME/.keys/* 

for f in $(ls $SSH_DIR); do
    enc_filename=$(echo $f | openssl aes-256-cbc -base64 -a -salt -pass pass:$pw | sed "s/\//%2F/g")
    # Encrypt ssh key and output to keys repo
    ansible-vault encrypt --output "$HOME/.keys/$enc_filename" --vault-password-file $HOME/.keys/scripts/pw "$SSH_DIR/$f"
done

rm $HOME/.keys/scripts/pw
