#!/usr/bin/env zsh

SSH_DIR="$HOME/.ssh"
# Create vault passwordfile
while [[ -z $pw ]]; do
    echo "Vault Password:"
    read pw
done

echo "Repeat Vault Password:"
read pw_check

# Check if passwords match
while [ "$pw" != "$pw_check" ]; do
    echo "Incorrect. Repeat Vault Password:"
    read pw_check
done

echo $pw > ./pw

for f in $(ls $SSH_DIR); do
    # Encrypt ssh key and output to keys repo
    ansible-vault encrypt --output "$HOME/.keys/$f" --vault-password-file ./pw "$SSH_DIR/$f"
done

rm ./pw
